pipeline {
    agent any

    tools {
        maven 'maven-3.9.3' // This should match the name you used in the Jenkins tool configuration
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
